# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20161017_1616'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('past_events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Series'),
        ),
    ]
