# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
