# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('events', '0009_event_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_eventlistpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('n_events', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
