# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 19:48
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('events', '0011_auto_20161016_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='map', to='cms.Placeholder'),
        ),
    ]
