# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20161017_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='only_future',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='only_past',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventlistpluginmodel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Use this instead of future/pastif you want a set date range', null=True),
        ),
    ]
