# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20161017_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlistpluginmodel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Only use this instead of future or past if you want a static date range', null=True),
        ),
    ]
