# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20161017_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlistpluginmodel',
            old_name='n_events',
            new_name='num_events',
        ),
        migrations.RenameField(
            model_name='eventlistpluginmodel',
            old_name='only_past',
            new_name='past_events',
        ),
        migrations.RemoveField(
            model_name='eventlistpluginmodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventlistpluginmodel',
            name='only_future',
        ),
        migrations.RemoveField(
            model_name='eventlistpluginmodel',
            name='series',
        ),
        migrations.RemoveField(
            model_name='eventlistpluginmodel',
            name='start_date',
        ),
    ]
