# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20161018_1504'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
    ]
