# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20161018_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlistpluginmodel',
            name='future_events',
            field=models.BooleanField(default=True),
        ),
    ]
