# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('startlist', models.FileField(upload_to='liveresults/')),
                ('resultslist', models.FileField(upload_to='liveresults/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveresults.Event')),
            ],
        ),
    ]
