# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rssplugin_rssplugin', serialize=False, to='cms.CMSPlugin')),
                ('count', models.IntegerField(default=6)),
                ('title', models.CharField(default='Community News', help_text="If you specified this value, it will replace feed's title", max_length=200, null=True)),
                ('rss_url', models.CharField(max_length=512)),
                ('open_in_new_window', models.BooleanField()),
                ('cache_time', models.IntegerField(verbose_name='Cache time in seconds')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
