# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-17 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('objectives', models.TextField()),
                ('standards', models.TextField(blank=True)),
                ('time_required', models.DurationField()),
                ('materials', models.TextField(blank=True)),
                ('prep', models.TextField(blank=True)),
                ('intro', models.TextField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
