# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20181223_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='execution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reflection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='variations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
