# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-28 20:34
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20181223_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='execution',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='variations',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
