# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-28 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20181228_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reflection',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
